In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('shipments_data.csv')
df

,идентификатор_отгрузки,идентификатор_контейнера,маршрут,дата_и_время_отправления,дата_и_время_прибытия,тип_груза,вес_груза,объем_груза,вместимость_контейнера,стоимость,доход,коэффициент_заполнения,имя_клиента
0,1,10031,Маршрут B,2023-07-05,2023-07-07 03:43:58.418323,Еда,17.247576,11.156925,30,374847.860369,351743.548676,0.371897,Клиент 7
1,2,10048,Маршрут B,2023-07-25,2023-07-28 00:49:58.580563,Еда,8.673310,15.992809,30,325972.421793,805164.963813,0.533094,Клиент 6
2,3,10020,Маршрут B,2023-07-10,2023-07-12 00:21:41.477812,Одежда,14.482027,13.082437,30,251301.571349,119811.827360,0.436081,Клиент 9
3,4,10030,Маршрут D,2023-07-02,2023-07-03 15:11:42.360935,Одежда,6.351304,13.845370,30,93576.727925,952490.781534,0.461512,Клиент 6
4,5,10014,Маршрут C,2023-07-14,2023-07-16 14:54:31.008820,Одежда,19.774484,28.675665,30,187207.529497,285140.922790,0.955856,Клиент 8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,10029,Маршрут A,2023-07-23,2023-07-23 23:27:57.069434,Мебель,13.699018,24.210163,30,97538.562113,522642.860734,0.807005,Клиент 3
96,97,10044,Маршрут A,2023-07-04,2023-07-05 20:49:45.862233,Мебель,13.294631,10.671929,30,265487.912710,624113.110638,0.355731,Клиент 2
97,98,10004,Маршрут A,2023-07-16,2023-07-19 02:20:13.552307,Еда,17.032170,13.256339,30,135266.789214,621993.014520,0.441878,Клиент 5
98,99,10038,Маршрут B,2023-07-02,2023-07-03 22:52:37.852781,Одежда,8.833083,29.738792,30,92318.366691,790419.635422,0.991293,Клиент 1
99,100,10045,Маршрут D,2023-07-21,2023-07-21 17:11:37.651258,Еда,5.701782,20.490300,30,388298.547676,668153.948487,0.683010,Клиент 2

In [10]:
# Группировка и агрегация
result = df.groupby('маршрут').agg({
    'вес_груза': ['mean', 'median', lambda x: pd.Series.mode(x).iloc[0] if not pd.Series.mode(x).empty else None],
    'объем_груза': ['mean', 'median', lambda x: pd.Series.mode(x).iloc[0] if not pd.Series.mode(x).empty else None],
    'доход': ['mean', 'median', lambda x: pd.Series.mode(x).iloc[0] if not pd.Series.mode(x).empty else None]
})

result.columns = ['_'.join(col).strip() for col in result.columns.values]
result.reset_index(inplace=True)

result

,маршрут,вес_груза_mean,вес_груза_median,вес_груза_<lambda_0>,объем_груза_mean,объем_груза_median,объем_груза_<lambda_0>,доход_mean,доход_median,доход_<lambda_0>
0,Маршрут A,13.999866,12.567243,6.131920,21.572581,22.553685,10.671929,561483.291225,621166.996430,224756.809066
1,Маршрут B,14.456047,13.195965,6.406445,20.166231,19.269889,11.156925,603019.183561,686530.055195,119811.827360
2,Маршрут C,13.635799,13.329833,5.352537,19.844172,20.414605,10.274134,561401.369630,602092.929198,138965.243543
3,Маршрут D,13.464652,13.577260,5.169889,20.141267,21.295677,10.407501,570566.586675,623718.533042,114982.126528

In [58]:
df['дата_и_время_прибытия'] = pd.to_datetime(df['дата_и_время_прибытия'])

df['дата_и_время_прибытия'] = df['дата_и_время_прибытия'].dt.date
df

,идентификатор_отгрузки,идентификатор_контейнера,маршрут,дата_и_время_отправления,дата_и_время_прибытия,тип_груза,вес_груза,объем_груза,вместимость_контейнера,стоимость,доход,коэффициент_заполнения,имя_клиента
0,1,10031,Маршрут B,2023-07-05,2023-07-07,Еда,17.247576,11.156925,30,374847.860369,351743.548676,0.371897,Клиент 7
1,2,10048,Маршрут B,2023-07-25,2023-07-28,Еда,8.673310,15.992809,30,325972.421793,805164.963813,0.533094,Клиент 6
2,3,10020,Маршрут B,2023-07-10,2023-07-12,Одежда,14.482027,13.082437,30,251301.571349,119811.827360,0.436081,Клиент 9
3,4,10030,Маршрут D,2023-07-02,2023-07-03,Одежда,6.351304,13.845370,30,93576.727925,952490.781534,0.461512,Клиент 6
4,5,10014,Маршрут C,2023-07-14,2023-07-16,Одежда,19.774484,28.675665,30,187207.529497,285140.922790,0.955856,Клиент 8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,10029,Маршрут A,2023-07-23,2023-07-23,Мебель,13.699018,24.210163,30,97538.562113,522642.860734,0.807005,Клиент 3
96,97,10044,Маршрут A,2023-07-04,2023-07-05,Мебель,13.294631,10.671929,30,265487.912710,624113.110638,0.355731,Клиент 2
97,98,10004,Маршрут A,2023-07-16,2023-07-19,Еда,17.032170,13.256339,30,135266.789214,621993.014520,0.441878,Клиент 5
98,99,10038,Маршрут B,2023-07-02,2023-07-03,Одежда,8.833083,29.738792,30,92318.366691,790419.635422,0.991293,Клиент 1
99,100,10045,Маршрут D,2023-07-21,2023-07-21,Еда,5.701782,20.490300,30,388298.547676,668153.948487,0.683010,Клиент 2

In [11]:
df = df.drop_duplicates()

In [12]:
columns_with_missing_values = ['доход', 'стоимость', 'тип_груза', 'маршрут']
mask = df[columns_with_missing_values].isna().any(axis=1)
rows_with_missing_values = df[mask]
df = df.dropna(subset=columns_with_missing_values)

In [15]:
# Метод на основе стандартного отклонения
def find_outliers_sd(df, columns, threshold=3):
    outliers = pd.DataFrame()
    for column in columns:
        mean = df[column].mean()
        std_dev = df[column].std()
        upper_bound = mean + threshold * std_dev
        lower_bound = mean - threshold * std_dev
        outliers = pd.concat([outliers, df[(df[column] > upper_bound) | (df[column] < lower_bound)]])
    return outliers.drop_duplicates()

# Метод на основе межквартильного размаха (IQR)
def find_outliers_iqr(df, columns, factor=1.5):
    outliers = pd.DataFrame()
    for column in columns:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        upper_bound = Q3 + factor * IQR
        lower_bound = Q1 - factor * IQR
        outliers = pd.concat([outliers, df[(df[column] > upper_bound) | (df[column] < lower_bound)]])
    return outliers.drop_duplicates()

# Определяем столбцы для проверки
numeric_columns = ['вес_груза', 'объем_груза', 'стоимость', 'доход']

# Поиск аномалий
outliers_sd = find_outliers_sd(df, numeric_columns)
outliers_iqr = find_outliers_iqr(df, numeric_columns)

print("Аномалии на основе стандартного отклонения:")
print(outliers_sd)

print("\nАномалии на основе межквартильного размаха (IQR):")
print(outliers_iqr)

Аномалии на основе стандартного отклонения:
Empty DataFrame
Columns: [идентификатор_отгрузки, идентификатор_контейнера, маршрут, дата_и_время_отправления, дата_и_время_прибытия, тип_груза, вес_груза, объем_груза, вместимость_контейнера, стоимость, доход, коэффициент_заполнения, имя_клиента]
Index: []

Аномалии на основе межквартильного размаха (IQR):
Empty DataFrame
Columns: [идентификатор_отгрузки, идентификатор_контейнера, маршрут, дата_и_время_отправления, дата_и_время_прибытия, тип_груза, вес_груза, объем_груза, вместимость_контейнера, стоимость, доход, коэффициент_заполнения, имя_клиента]
Index: []

In [45]:
# Вычисление метрик с использованием медианы
metrics = {
    'Доход на отгрузку': round(df['доход'].mean(),2),
    'Стоимость на отгрузку': round(df['стоимость'].mean(),2),
    'Общая валовая прибыль': round(df['доход'].sum() - df['стоимость'].sum(),2),
    'Общая сумма продаж': round(df['доход'].sum(),2),
    'Коэффициент заполнения 1 контейнера': int(df['коэффициент_заполнения'].mean()*100),
    'Процент окупаемости контейнера':round(((df['доход'].mean() - (df['стоимость'].mean())) / (20_000_000)) * 100,2)
}

In [47]:
# Печать результатов
print("Бизнес-метрики:")
for key, value in metrics.items():
    print(f"{key}: {value}")

Бизнес-метрики:
Доход на отгрузку: 573647.76
Стоимость на отгрузку: 256399.33
Общая валовая прибыль: 31724843.91
Общая сумма продаж: 57364776.41
Коэффициент заполнения 1 контейнера: 67
Процент окупаемости контейнера: 1.59

In [51]:
!pip install dash
!pip install plotly

Requirement already satisfied: dash in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (2.17.1)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (2.2.3)
Requirement already satisfied: Werkzeug<3.1 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (2.2.3)
Requirement already satisfied: plotly>=5.0.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (5.14.1)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (5.0.0)
Requirement already satisfied: importlib-metadata in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (6.8.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (4.11.0)
Requirement already satisfied: requests in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (2.31.0)
Requirement already satisfied: retrying in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (1.5.8)
Requirement already satisfied: setuptools in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from dash) (65.5.0)
Requirement already satisfied: Jinja2>=3.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (2.1.2)
Requirement already satisfied: click>=8.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (8.1.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from plotly>=5.0.0->dash) (8.2.2)
Requirement already satisfied: packaging in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from plotly>=5.0.0->dash) (23.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from Werkzeug<3.1->dash) (2.1.2)
Requirement already satisfied: zipp>=0.5 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from importlib-metadata->dash) (3.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from requests->dash) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from requests->dash) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from requests->dash) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from requests->dash) (2022.12.7)
Requirement already satisfied: six>=1.7.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from retrying->dash) (1.16.0)
Requirement already satisfied: colorama in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from click>=8.0->Flask<3.1,>=1.0.4->dash) (0.4.6)

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: plotly in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (5.14.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from plotly) (8.2.2)
Requirement already satisfied: packaging in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (from plotly) (23.0)

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [54]:
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

C:\Users\79045\AppData\Local\Temp\ipykernel_6120\3822179843.py:3: UserWarning:


The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`

C:\Users\79045\AppData\Local\Temp\ipykernel_6120\3822179843.py:4: UserWarning:


The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`

In [62]:
metrics

{'Доход на отгрузку': 573647.76,
 'Стоимость на отгрузку': 256399.33,
 'Общая валовая прибыль': 31724843.91,
 'Общая сумма продаж': 57364776.41,
 'Коэффициент заполнения 1 контейнера': 67,
 'Процент окупаемости контейнера': 1.59}

In [85]:
# Инициализация Dash
app = dash.Dash(__name__)

# Сортировка данных для графика по клиентам
sorted_df = df.groupby('имя_клиента')['доход'].sum().reset_index()
sorted_df = sorted_df.sort_values(by='доход', ascending=True)

formatted_metrics = {key: "{:,.2f}".format(value).replace(',', ' ') for key, value in metrics.items()}

# Создание графиков
fig_доход_по_дням = px.bar(df.groupby('дата_и_время_прибытия')['доход'].sum().reset_index(), x='дата_и_время_прибытия', y='доход', title='Сумма продаж за день')
fig_доход_по_маршрутам = px.pie(df.groupby('маршрут')['доход'].sum().reset_index(), names='маршрут', values='доход', title='Сумма продаж по маршруту')
fig_доход_по_клиентам = px.bar(sorted_df, y='имя_клиента', x='доход', title='Сумма продаж по клиентам')

# Определение макета дашборда
app.layout = html.Div([
    html.H1('Интерактивный Дашборд'),

    # Карточки метрик
    html.Div([
        html.Div([
            html.H3('Доход на отгрузку'),
            html.P(f'{formatted_metrics["Доход на отгрузку"]} ₽'),
        ], className='card'),

        html.Div([
            html.H3('Стоимость на отгрузку'),
            html.P(f'{formatted_metrics["Стоимость на отгрузку"]} ₽'),
        ], className='card'),

        html.Div([
            html.H3('Общая валовая прибыль'),
            html.P(f'{formatted_metrics["Общая валовая прибыль"]} ₽'),
        ], className='card'),

        html.Div([
            html.H3('Общая сумма продаж'),
            html.P(f'{formatted_metrics["Общая сумма продаж"]} ₽'),
        ], className='card'),

        html.Div([
            html.H3('Коэффициент заполнения 1 контейнера'),
            html.P(f'{formatted_metrics["Коэффициент заполнения 1 контейнера"]}'),
        ], className='card'),

        html.Div([
            html.H3('Процент окупаемости контейнера'),
            html.P(f'{formatted_metrics["Процент окупаемости контейнера"]}%'),
        ], className='card'),
    ], style={'display': 'flex', 'flexWrap': 'wrap', 'gap': '20px'}),
    
    # Графики
    dcc.Graph(figure=fig_доход_по_дням),
    dcc.Graph(figure=fig_доход_по_маршрутам),
    dcc.Graph(figure=fig_доход_по_клиентам),
], style={'display': 'flex', 'flexWrap': 'wrap', 'gap': '20px'})

# Запуск приложения
if __name__ == '__main__':
    app.run_server(debug=True)